services:
  # Web Service
  - type: web
    name: binance-smart-mail
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install --legacy-peer-deps && npx prisma generate && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 20.13.1
      - key: DATABASE_URL
        fromDatabase:
          name: binance-smart-mail-db
          property: connectionString
      - key: NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID
        value: a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6
      - key: NEXT_PUBLIC_NETWORK
        value: mainnet
      - key: NEXT_PUBLIC_BSM_CONTRACT
        value: 0x0000000000000000000000000000000000000000

databases:
  - name: binance-smart-mail-db
    databaseName: binance_smart_mail
    plan: free
    region: oregon

