services:
  # Web Service
  - type: web
    name: binance-smart-mail
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run db:generate && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 20.13.1
      - key: DATABASE_URL
        fromDatabase:
          name: binance-smart-mail-db
          property: connectionString
      - key: NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID
        sync: false
      - key: NEXT_PUBLIC_NETWORK
        value: mainnet
      - key: NEXT_PUBLIC_BSM_CONTRACT
        value: 0x0000000000000000000000000000000000000000

databases:
  - name: binance-smart-mail-db
    databaseName: binance_smart_mail
    plan: free
    region: oregon

